import Portfolio from './Portfolio';

export default function App() {
  return <Portfolio />; /*
  const [data, setData] = useState(null);
  const [dark, setDark] = useState(false);
  useEffect(() => { fetch('/db.json').then((response) => response.json()).then(setData).catch(console.error); }, []);
  useEffect(() => { document.documentElement.dataset.theme = dark ? 'dark' : 'light'; }, [dark]);
  if (!data) return <main className="loading">Loading portfolio…</main>;
  const { profile, summary, skills, softSkills, projects, experience, education, certificates } = data;
  return <><header className="site-header"><div className="container nav-wrap"><a href="#top" className="brand">{profile.name}<span>.</span></a><nav>{['About', 'Projects', 'Experience', 'Contact'].map((item) => <a key={item} href={`#${item.toLowerCase()}`}>{item}</a>)}</nav><div className="nav-actions"><button className="icon-button" onClick={() => setDark(!dark)} aria-label="Toggle colour theme">{dark ? <Sun size={18} /> : <Moon size={18} />}</button><a className="button button-small" href={`https://${profile.linkedin}`} target="_blank" rel="noreferrer">LinkedIn</a></div></div></header><main>
    <section id="top" className="hero"><div className="container hero-content"><p className="eyebrow">{profile.title}</p><h1>{profile.name}</h1><p className="hero-summary">{summary}</p><div className="hero-meta"><span><MapPin size={16} /> {profile.location}</span><a href={`mailto:${profile.email}`}>{profile.email}</a></div><div className="tag-list">{skills.map((item) => <span className="tag" key={item}>{item}</span>)}</div><a href="#projects" className="button">View projects ↓</a></div></section>
    <section id="about" className="section section-muted"><div className="container split-section"><div><p className="eyebrow">Profile</p><h2>A practical frontend developer.</h2></div><div><p className="body-copy">{summary}</p><h3>Technical skills</h3><div className="tag-list">{skills.map((item) => <span className="tag" key={item}>{item}</span>)}</div><h3>Strengths</h3><div className="strengths">{softSkills.map((item) => <span key={item}>{item}</span>)}</div></div></div></section>
    <section id="projects" className="section"><div className="container"><p className="eyebrow">Selected work</p><h2>Projects from my resume.</h2><div className="project-list">{projects.map((project) => <article className="project-card" key={project.title}><div><p className="project-number">0{project.id}</p><h3>{project.title}</h3><p className="project-description">{project.description}</p></div><div><div className="tag-list">{project.technologies.map((item) => <span className="tag" key={item}>{item}</span>)}</div><p className="project-detail">{project.highlight}</p></div></article>)}</div></div></section>
    <section id="experience" className="section section-muted"><div className="container"><p className="eyebrow">Background</p><h2>Experience and education.</h2><div className="two-column"><div><h3 className="list-heading">Experience</h3>{experience.map((item) => <article className="timeline-item" key={item.company}><p className="item-date">{item.period}</p><h3>{item.company}</h3><p className="item-subtitle">{item.location}</p><ul>{item.highlights.map((highlight) => <li key={highlight}>{highlight}</li>)}</ul></article>)}</div><div><h3 className="list-heading">Education</h3>{education.map((item) => <article className="timeline-item" key={item.degree}><p className="item-date">{item.year}</p><h3>{item.degree}</h3><p className="item-subtitle">{item.institution} · {item.location}</p></article>)}</div></div></div></section>
    <section id="contact" className="section"><div className="container contact-panel"><div><p className="eyebrow">Contact</p><h2>Let’s connect.</h2><p className="body-copy">For an opportunity or project discussion, reach out directly.</p></div><div className="contact-links"><a href={`mailto:${profile.email}`}><Mail size={18} />{profile.email}</a><a href={`tel:${profile.phone}`}><Phone size={18} />{profile.phone}</a><a href={`https://${profile.linkedin}`} target="_blank" rel="noreferrer">LinkedIn</a></div><div className="certificates"><p className="eyebrow">Courses & certificates</p>{certificates.map((item) => <p key={item}>{item}</p>)}</div></div></section>
  </main><footer><div className="container"><span>© {new Date().getFullYear()} {profile.name}</span><a href="#top">Back to top ↑</a></div></footer></>;
*/}
